### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by hokster7** [PaulSolt/CompositeXib#1]
I followed Part 1 of the XIB loading instructions and ran a test application.

I got a `EXC_BAD_ACCESS` on the line

``` objc
    self = [super initWithCoder:coder];
```

**Comment by hokster7** [comment]
I loaded it from a storyboard.

**Comment by hokster7** [comment]
I fixed it!!

It had nothing to do with the storyboard.

Let's say my custom view is called `WidgetView`.
1. Says that you should "Set Files Owner for .xib to WidgetView". What I effectively did was accidentally set the `UIView`'s class to `WidgetView` as well. This caused the error. Now everything loads fine.

**Comment by PaulSolt** [comment]
Glad you figured it out.

You can accidentally shoot yourself in the foot, if you miss-click in the
storyboard file.

-Paul

On Fri, Oct 31, 2014 at 12:03 PM, Hok Shun Poon notifications@github.com
wrote:

> I fixed it!!
> 
> It had nothing to do with the storyboard.
> 
> Let's say my custom view is called WidgetView.
> 1. Says that you should "Set Files Owner for .xib to WidgetView". What
>    I effectively did was accidentally set the UIView's class to WidgetView
>    as well. This caused the error. Now everything loads fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PaulSolt/CompositeXib/issues/1#issuecomment-61283017.

## 

Paul Solt
PaulSolt@gmail.com
215-341-0407 (Cell)
http://www.PaulSolt.com/

Creative apps for iPhone and iPad: http://www.ArtworkEvolution.com/
