### ISSUE TITLE
Resizable composite XIB-based components

### ISSUE THREAD

**Issue by hokster7** [PaulSolt/CompositeXib#2]
Hi,

So, I've managed to make a scalable keypad component in a `.xib` I'm fairly proud of:

![screen shot 2014-11-01 at 11 52 57](https://cloud.githubusercontent.com/assets/430233/4871544/a3df1a6c-61bd-11e4-8aed-d5ff57c4fb66.png)

The buttons' (and rows of buttons') autolayout makes the sizing of the buttons be determined by the width and the height of the root view — i.e. you can give it any width and height and the buttons should just readjust themselves to fit!

I want to stick a small version of the numberpad (300x300) into the middle of my storyboard (coloured torquoise here) so I create a view (complete with width and height constraints) and set the numberpad xib class on it.

![screen shot 2014-11-01 at 11 55 41](https://cloud.githubusercontent.com/assets/430233/4871553/07689856-61be-11e4-8106-ebe89b2bc8a2.png)

Sure enough, it's loaded, but when I run it, the sizing is totally wrong:

![ios simulator screen shot 1 nov 2014 11 56 28](https://cloud.githubusercontent.com/assets/430233/4871555/2301088c-61be-11e4-9366-cf1ca05e5ce9.png)

It's basically just taken the provisional 600x600 dimensions from the XIB rather than using the 300x300 view frame I specified in the storyboard.

Any ideas why it's not sized according to the frame I drew in the storyboard?

**Comment by hokster7** [comment]
Hmm. I need to pin the four sides of the subview to the four sides of the view. This is clear when I turn on Clip Subviews.

![ios simulator screen shot 1 nov 2014 12 03 17](https://cloud.githubusercontent.com/assets/430233/4871581/3a46ded0-61bf-11e4-98bc-50d48679692e.png)

**Comment by hokster7** [comment]
I figured it out — again!! Thanks @PaulSolt for [your super informative video(s)](https://www.youtube.com/watch?v=xP7YvdlnHfA).

The issue was that I thought the `View` in the XIB _was_ represented by the turquoise  `UIView` I drew up in the storyboard. This is untrue. There is an extra layer of hierarchy, a fact hinted at by the need for this line:

``` objc
    [self addSubview:view]
```

So actually we've got a view, that contains the `View` in the XIB.

The solution for me was simple: I use [Masonry](https://github.com/Masonry/Masonry/) to pin the edges of the inner view to the outer view.

``` objc
- (void)setup {
    [[NSBundle mainBundle] loadNibNamed:@"MESNumberPad" owner:self options:nil];

    [self addSubview:self.view];

    [self.view mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self);
    }];
}
```

![ios simulator screen shot 1 nov 2014 12 37 12](https://cloud.githubusercontent.com/assets/430233/4871674/cfbd7ae2-61c3-11e4-9059-7eb3ba638277.png)

Et violà.

**Comment by PaulSolt** [comment]
Nice work!

On Sat, Nov 1, 2014 at 8:37 AM, Hok Shun Poon notifications@github.com
wrote:

> I figured it out — again!! Thanks @PaulSolt https://github.com/PaulSolt
> for your super informative video(s)
> https://www.youtube.com/watch?v=xP7YvdlnHfA.
> 
> The issue was that I thought the View in the XIB _was_ represented by the
> turquoise UIView I drew up in the storyboard. This is untrue. There is an
> extra layer of hierarchy, a fact hinted at by the need for this line:
> 
> ```
> [self addSubview:view]
> ```
> 
> So actually we've got a view, that contains the View in the XIB.
> 
> The solution for me was simple: I use Masonry
> https://github.com/Masonry/Masonry/ to pin the edges of the inner view
> to the outer view.
> - (void)setup {
>   [[NSBundle mainBundle] loadNibNamed:@"MESNumberPad" owner:self options:nil];
>   
>   [self addSubview:self.view];
>   
>   [self.view mas_makeConstraints:^(MASConstraintMaker *make) {
>       make.edges.equalTo(self);
>   }];}
> 
> [image: ios simulator screen shot 1 nov 2014 12 37 12]
> https://cloud.githubusercontent.com/assets/430233/4871674/cfbd7ae2-61c3-11e4-9059-7eb3ba638277.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PaulSolt/CompositeXib/issues/2#issuecomment-61366920.

## 

Paul Solt
PaulSolt@gmail.com
215-341-0407 (Cell)
http://www.PaulSolt.com/

Creative apps for iPhone and iPad: http://www.ArtworkEvolution.com/
